import { fileType } from "../helpers/utils";
import execs from "../helpers/commands/execs";

const execContent = "Error: can not print an executable file.";

export const files = {
    "about.txt": {
        name: "about.txt",
        content: [
            "Hi there 👋 I'm Tom Klimovski, Principal at Gamma Data (https://gammadata.io).",
            "We build Data Platforms for the Enterprise.",
            "",
            "-----",
            "Using and manipulating Data in the cloud is what excites me.",
            "I am a specialist GCP consultant with a 20-year history in IT, including a decade of",
            "enterprise-scale GCP implementations for the likes of:",
            "● Cleanaway — Tech Lead",
            "● Bendigo Bank — Tech Lead",
            "● Wesfarmers Health",
            "● ANZ Bank",
            "Startups I've helped with include notion.ai & gopassport.health",
            "",
            "-----",
            "Things we've done at gammadata.io:",
            "● Gitlab/Prefect/Vault/Salesforce/BigQuery/dbt/PowerBI",
            "● Delivered solutions with:",
            "...o High durability of data",
            "...o Robust pipelines and documentation that catch issues early",
            "...o Completely configurable, pythonic syntax for easy debugging",
            "...o ELT architecture on top of a GCP Data Lake",
            "",
            "-----",
            "🚀 Outside of Gamma Data entirely, I'm Co-Founder & Director of Technology",
            "at TectoniQ (https://tectoniq.com.au) — an independent venture.",
            "A strategic talent advisory powered by TIQ, our unified talent intelligence platform —",
            "helping organisations attract, assess, recruit and develop early talent.",
            "",
            "-----",
            "My side projects include",
            "✊ epicarc.io",
            "✊ skicounselling.com",
            "✊ sleeplikegoldilocks.com",
            "",
            "-----",
            "🔭 I’m currently Tech Lead & AI Architect at Cleanaway, and building TIQ at TectoniQ",
            "🌱 I’m currently learning how far AI coding agents can be pushed. Always learning",
            "👯 I’m looking to collaborate on tools that make automation possible",
            "🤔 I’m looking for help with automating Data Governance",
            "💬 Ask me about Delivering Technical Projects",
            "   Read my blog here: https://medium.com/@tom.klimovski",
            "      And here: https://medium.com/@tom.klimovski_90944",
            "------",
        ],
        type: fileType.regular,
        longView: 'r--',
    },
    "cowsay": {
        name: "cowsay",
        content: [execContent],
        type: fileType.exec,
        run: execs['cowsay'],
        longView: 'r-x',
    },
    "do-not-run-me": {
        name: "do-not-run-me",
        content: [execContent],
        type: fileType.exec,
        run: execs['rick-roll'],
        longView: 'r-x',
    },
}
